// SPDX-License-Identifier: Apache-2.0
use crate::proof_of_origin::{Attestation, ProofOfOriginContractRef, Verdict};
use odra::prelude::*;
use odra::ContractRef;

/// Business errors for MintGate.
///
/// `#[odra::odra_error]` generates the conversion into `OdraError`, allowing
/// readable revert names in OdraVM tests.
#[odra::odra_error]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum MintGateError {
    /// Only the owner may execute the action.
    NotOwner,
    /// No valid ProofOfOrigin proof exists for the requested lot.
    NoValidProof,
    /// The lot has already been tokenized/registered in this gate.
    AlreadyMinted,
}

/// Event emitted when a lot passes the gate and is marked as tokenized.
#[odra::event]
pub struct LotMinted {
    pub asset_id: String,
    pub minter: Address,
}

/// On-chain gate that consumes the `ProofOfOrigin` proof.
///
/// It does not create a real token yet; in this block, "minting" is symbolic:
/// it records that an `asset_id` passed the gate after valid proof.
#[odra::module(events = [LotMinted], errors = MintGateError)]
pub struct MintGate {
    /// Gate owner/admin, set in `init` to the deploy caller.
    owner: Var<Address>,
    /// Address of the ProofOfOrigin contract queried by this gate.
    proof_contract: Var<Address>,
    /// Anti-duplication control: asset_id -> already tokenized?
    minted: Mapping<String, bool>,
    /// Total lots tokenized/registered by the gate.
    mint_count: Var<u32>,
}

#[odra::module]
impl MintGate {
    /// Odra constructor.
    ///
    /// Stores the initial owner and `ProofOfOrigin` address, then resets the counter.
    pub fn init(&mut self, proof_contract: Address) {
        self.owner.set(self.env().caller());
        self.proof_contract.set(proof_contract);
        self.mint_count.set(0);
    }

    /// Updates the `ProofOfOrigin` contract queried by this gate.
    ///
    /// Only the owner may change this dependency.
    pub fn set_proof_contract(&mut self, proof_contract: Address) {
        self.ensure_owner();
        self.proof_contract.set(proof_contract);
    }

    /// Symbolically tokenizes/registers a lot only when valid proof exists.
    ///
    /// Flow:
    /// 1. blocks double minting (`AlreadyMinted`);
    /// 2. queries `ProofOfOrigin.get_attestation(asset_id)` by cross-contract call;
    /// 3. requires `Some(attestation)` with `verdict == Verdict::Valid`;
    /// 4. writes `minted`, increments the counter, and emits an event.
    pub fn mint_lot(&mut self, asset_id: String) {
        if self.is_minted(asset_id.clone()) {
            self.env().revert(MintGateError::AlreadyMinted);
        }

        let attestation = self.get_origin_attestation(asset_id.clone());
        match attestation {
            Some(attestation) if attestation.verdict == Verdict::Valid => {
                self.minted.set(&asset_id, true);
                self.mint_count.add(1);

                self.env().emit_event(LotMinted {
                    asset_id,
                    minter: self.env().caller(),
                });
            }
            _ => self.env().revert(MintGateError::NoValidProof),
        }
    }

    /// Returns `true` if the lot has already been tokenized/registered in this gate.
    pub fn is_minted(&self, asset_id: String) -> bool {
        self.minted.get_or_default(&asset_id)
    }

    /// Total lots tokenized/registered by the gate.
    pub fn mint_count(&self) -> u32 {
        self.mint_count.get_or_default()
    }

    /// Owner/admin set at deploy time.
    pub fn get_owner(&self) -> Address {
        self.owner.get().unwrap_or_revert(self)
    }

    /// Current `ProofOfOrigin` contract address used for queries.
    pub fn get_proof_contract(&self) -> Address {
        self.proof_contract.get().unwrap_or_revert(self)
    }

    /// Internal helper that keeps the owner rule in one place.
    fn ensure_owner(&self) {
        if self.env().caller() != self.get_owner() {
            self.env().revert(MintGateError::NotOwner);
        }
    }

    /// Queries the configured `ProofOfOrigin` using the `ContractRef` generated by Odra.
    ///
    /// The `#[odra::module]` macro on `ProofOfOrigin` generates
    /// `ProofOfOriginContractRef`. In Odra 2.8, that ref is created with
    /// `ProofOfOriginContractRef::new(env, address)`, where `env` is the caller
    /// contract environment (`self.env()`) and `address` is the address saved in storage.
    fn get_origin_attestation(&self, asset_id: String) -> Option<Attestation> {
        let proof = ProofOfOriginContractRef::new(self.env(), self.get_proof_contract());
        proof.get_attestation(asset_id)
    }
}

#[cfg(test)]
mod tests {
    use crate::mint_gate::{LotMinted, MintGate, MintGateError, MintGateInitArgs};
    use crate::proof_of_origin::ProofOfOrigin;
    use odra::host::{Deployer, NoArgs};
    use odra::prelude::{Addressable, OdraError};

    fn asset_id() -> String {
        String::from("MINA-VALEDOURO-LOTE-001")
    }

    fn second_asset_id() -> String {
        String::from("MINA-VALEDOURO-LOTE-002")
    }

    fn valid_seal() -> String {
        String::from("a3f1c9b8d7e6f50123456789abcdef00112233445566778899aabbccddeeff00")
    }

    fn invalid_seal() -> String {
        String::from("fffec9b8d7e6f50123456789abcdef00112233445566778899aabbccddeeff11")
    }

    /// Default deployment for both contracts.
    ///
    /// `MintGate` receives the `ProofOfOrigin` address in init, exactly as it
    /// would on-chain.
    fn deploy_contracts() -> (
        odra::host::HostEnv,
        crate::proof_of_origin::ProofOfOriginHostRef,
        crate::mint_gate::MintGateHostRef,
    ) {
        let env = odra_test::env();
        let owner = env.get_account(0);
        env.set_caller(owner);

        let proof = ProofOfOrigin::deploy(&env, NoArgs);
        let gate = MintGate::deploy(
            &env,
            MintGateInitArgs {
                proof_contract: proof.address(),
            },
        );

        (env, proof, gate)
    }

    #[test]
    fn valid_attestation_allows_mint_lot() {
        let (env, mut proof, mut gate) = deploy_contracts();
        let minter = env.get_account(1);

        proof.register_reference(asset_id(), valid_seal());

        env.set_caller(minter);
        proof.attest(asset_id(), valid_seal());
        gate.mint_lot(asset_id());

        assert!(gate.is_minted(asset_id()));
        assert_eq!(gate.mint_count(), 1);
        assert!(env.emitted_event(
            &gate,
            LotMinted {
                asset_id: asset_id(),
                minter,
            }
        ));
    }

    #[test]
    fn invalid_attestation_reverts_with_no_valid_proof() {
        let (env, mut proof, mut gate) = deploy_contracts();
        let minter = env.get_account(1);

        proof.register_reference(asset_id(), valid_seal());

        env.set_caller(minter);
        proof.attest(asset_id(), invalid_seal());
        let err = gate.try_mint_lot(asset_id()).unwrap_err();

        let expected: OdraError = MintGateError::NoValidProof.into();
        assert_eq!(err, expected);
        assert!(!gate.is_minted(asset_id()));
        assert_eq!(gate.mint_count(), 0);
    }

    #[test]
    fn asset_without_attestation_reverts_with_no_valid_proof() {
        let (env, _proof, mut gate) = deploy_contracts();
        let minter = env.get_account(1);

        env.set_caller(minter);
        let err = gate.try_mint_lot(second_asset_id()).unwrap_err();

        let expected: OdraError = MintGateError::NoValidProof.into();
        assert_eq!(err, expected);
        assert!(!gate.is_minted(second_asset_id()));
        assert_eq!(gate.mint_count(), 0);
    }

    #[test]
    fn minting_same_valid_asset_twice_reverts_with_already_minted() {
        let (env, mut proof, mut gate) = deploy_contracts();
        let minter = env.get_account(1);

        proof.register_reference(asset_id(), valid_seal());

        env.set_caller(minter);
        proof.attest(asset_id(), valid_seal());
        gate.mint_lot(asset_id());

        let err = gate.try_mint_lot(asset_id()).unwrap_err();

        let expected: OdraError = MintGateError::AlreadyMinted.into();
        assert_eq!(err, expected);
        assert!(gate.is_minted(asset_id()));
        assert_eq!(gate.mint_count(), 1);
    }

    #[test]
    fn set_proof_contract_from_non_owner_reverts_with_not_owner() {
        let (env, proof, mut gate) = deploy_contracts();
        let non_owner = env.get_account(1);

        env.set_caller(non_owner);
        let err = gate.try_set_proof_contract(proof.address()).unwrap_err();

        let expected: OdraError = MintGateError::NotOwner.into();
        assert_eq!(err, expected);
        assert_eq!(gate.get_proof_contract(), proof.address());
    }
}
