import type { Operation } from "./types";

const observed = (
  id: string,
  name: string,
  transport: string,
  symbol: string,
  effects: string[],
  notes: string,
): Operation => ({
  id,
  name,
  status: "observed",
  transport,
  source: "app/src/lib/api.ts",
  symbol,
  effects,
  errors: [],
  notes,
});
const proposed = (
  id: string,
  name: string,
  effects: string[],
  errors: string[],
  notes: string,
): Operation => ({
  id,
  name,
  status: "proposed",
  transport: null,
  source: null,
  symbol: null,
  effects,
  errors,
  notes,
});

/** Observed API functions are NOT shared, validated operation contracts yet. */
export const operations: Operation[] = [
  {
    id: "lote.importar",
    name: "Importar lotes por CSV",
    status: "observed",
    transport: "POST /api/assets/objects/import",
    source: "app/server/assets/store.ts",
    symbol: "AssetsStore.importLots",
    effects: ["escrita", "importacao"],
    errors: ["FORBIDDEN", "INVALID_INPUT", "STALE_REVISION", "UNAVAILABLE"],
    notes:
      "Até 100 lotes; valida todas as linhas antes de gravar. Repetição com a mesma chave não duplica cadastros. Campos vêm do CSV revisado na interface.",
  },
  {
    id: "versao.exportar",
    name: "Exportar resumo identificado",
    status: "observed",
    transport: "GET /api/assets/objects/:id/versions/:versionId/export",
    source: "app/server/assets/store.ts",
    symbol: "AssetsStore.exportVersion",
    effects: ["leitura", "exportacao"],
    errors: ["FORBIDDEN", "INVALID_INPUT", "STALE_REVISION", "UNAVAILABLE"],
    notes:
      "Exporta JSON da versão imutável com organização, autoria, data e limites; registra evento. Somente organização de origem e escopo autorizado.",
  },
  {
    id: "organizacao.alternar",
    name: "Alternar organização ativa",
    status: "observed",
    transport: "POST /api/assets/switch-organization",
    source: "app/server/assets/store.ts",
    symbol: "AssetsStore.switchOrganization",
    effects: ["identidade", "permissao"],
    errors: ["FORBIDDEN", "INVALID_INPUT", "STALE_REVISION", "UNAVAILABLE"],
    notes:
      "Confere participação ativa e cria sessão para a organização escolhida. Não transfere cadastros nem permissões entre empresas.",
  },
  {
    id: "destinatario.conferir",
    name: "Conferir organização destinatária",
    status: "observed",
    transport: "GET /api/assets/recipients?email=:email",
    source: "app/server/assets/store.ts",
    symbol: "AssetsStore.recipients",
    effects: ["leitura"],
    errors: ["FORBIDDEN", "INVALID_INPUT", "STALE_REVISION", "UNAVAILABLE"],
    notes:
      "Retorna organizações de destino elegíveis para o contato; seleção explícita evita compartilhar com a empresa errada quando existem vários vínculos.",
  },
  observed(
    "lote.listar",
    "Listar lotes",
    "GET /api/lots",
    "getLots",
    ["leitura"],
    "API do runtime demonstrativo. Não comprova persistência durável ou isolamento por organização.",
  ),
  observed(
    "lote.consultar",
    "Consultar lote",
    "GET /api/lots/:assetId",
    "getLot",
    ["leitura", "fallback-demo"],
    "getLot pode retornar catálogo local após 404 e aplica dados de mint demonstrativo.",
  ),
  observed(
    "artefato.criar",
    "Criar artefato",
    "POST /api/artifacts",
    "createArtifact",
    ["escrita"],
    "Entrada tipada como any no cliente atual; contrato de domínio ainda pendente.",
  ),
  observed(
    "selo.calcular",
    "Calcular selo",
    "POST /api/seal",
    "computeSealForArtifact",
    ["verificacao"],
    "Integridade determinística. Um selo não comprova sozinho a existência física do ativo.",
  ),
  observed(
    "lote.processar",
    "Processar lotes",
    "POST /api/process/batch",
    "processBatch",
    ["escrita", "verificacao"],
    "Ação do agente e veredito do selo têm significados distintos.",
  ),
  observed(
    "auditoria.listar",
    "Listar auditoria",
    "GET /api/audit",
    "getAudit",
    ["leitura"],
    "Histórico técnico do console; não equivale à decisão de um analista no Investors.",
  ),
  observed(
    "auditoria.consultar",
    "Consultar auditoria",
    "GET /api/audit/:assetId",
    "getAuditRecord",
    ["leitura", "fallback-demo"],
    "Pode responder com registro demonstrativo local após 404.",
  ),
  observed(
    "excecao.listar",
    "Listar exceções",
    "GET /api/escalations",
    "getEscalations",
    ["leitura"],
    "Revisão operacional. Ações de requeue, discard e override ainda precisam de fichas próprias.",
  ),
  observed(
    "configuracao.atualizar",
    "Atualizar modo do agente",
    "POST /api/settings",
    "updateSettings",
    ["escrita"],
    "Configuração do runtime compartilhado; não representa configuração por organização.",
  ),
  observed(
    "mint.simular",
    "Registrar mint demonstrativo",
    "POST /api/mint",
    "mintAsset",
    ["escrita", "simulacao"],
    "Mint de sessão não deve ser apresentado como transação Casper confirmada.",
  ),
  observed(
    "rail.simular",
    "Executar demonstração completa",
    "POST /api/rail/run",
    "runSealedRailDemo",
    ["escrita", "simulacao"],
    "O caminho rail/run permanece mock, independentemente do modo do facilitador.",
  ),
  observed(
    "consulta.simular",
    "Simular consulta x402",
    "POST /api/x402/simulate/:assetId",
    "simulateAgentQuery",
    ["simulacao"],
    "Simulação não movimenta valor; settle é outro transporte e exige ficha separada.",
  ),
  {
    id: "assets.consultar",
    name: "Consultar workspace",
    status: "observed",
    transport: "GET /api/assets/workspace",
    source: "app/server/assets/store.ts",
    symbol: "AssetsStore.workspace",
    effects: ["leitura"],
    errors: [
      "SESSION_EXPIRED",
      "FORBIDDEN",
      "STALE_REVISION",
      "INVALID_INPUT",
      "UNAVAILABLE",
    ],
    notes:
      "Retorna somente organização e escopo da sessão; sem fallback demonstrativo. Persistência local; não certifica operação distribuída.",
  },
  {
    id: "assets.autenticar",
    name: "Autenticar em Assets",
    status: "observed",
    transport: "POST /api/assets/{login,register,demo,logout}",
    source: "app/server/assets/store.ts",
    symbol: "AssetsStore.login",
    effects: ["identidade"],
    errors: [
      "SESSION_EXPIRED",
      "FORBIDDEN",
      "STALE_REVISION",
      "INVALID_INPUT",
      "UNAVAILABLE",
    ],
    notes:
      "Sessão HttpOnly; senha scrypt; conta e organização persistidas localmente. Não inclui confirmação de e-mail nem recuperação de senha. Persistência local; não certifica operação distribuída.",
  },
  {
    id: "assets.salvar",
    name: "Salvar e organizar cadastro",
    status: "observed",
    transport: "POST /api/assets/objects[/:id[/status]]",
    source: "app/server/assets/store.ts",
    symbol: "AssetsStore.updateObject",
    effects: ["escrita", "versionamento"],
    errors: [
      "SESSION_EXPIRED",
      "FORBIDDEN",
      "STALE_REVISION",
      "INVALID_INPUT",
      "UNAVAILABLE",
    ],
    notes:
      "Rascunho incompleto permitido; revisão otimista impede sobrescrita. Arquivamento mantém versões e acessos. Persistência local; não certifica operação distribuída.",
  },
  {
    id: "evidencia.anexar",
    name: "Anexar evidência identificada",
    status: "observed",
    transport: "POST /api/assets/objects/:id/evidence",
    source: "app/server/assets/store.ts",
    symbol: "AssetsStore.upload",
    effects: ["escrita", "arquivo"],
    errors: [
      "SESSION_EXPIRED",
      "FORBIDDEN",
      "STALE_REVISION",
      "INVALID_INPUT",
      "UNAVAILABLE",
    ],
    notes:
      "PDF/JPG/PNG/TXT até 8 MB; bytes e metadados persistidos no servidor; SHA-256 conferido no envio; substituição mantém snapshots. Persistência local; não certifica operação distribuída.",
  },
  {
    id: "solicitacao.responder",
    name: "Responder solicitação",
    status: "observed",
    transport: "POST /api/assets/requests/:id",
    source: "app/server/assets/store.ts",
    symbol: "AssetsStore.updateRequest",
    effects: ["escrita", "texto-livre"],
    errors: [
      "SESSION_EXPIRED",
      "FORBIDDEN",
      "STALE_REVISION",
      "INVALID_INPUT",
      "UNAVAILABLE",
    ],
    notes:
      "Vincula cadastro, justificativas permitidas e respostas; compartilhar é outra operação. Responder não resolve a análise. Persistência local; não certifica operação distribuída.",
  },
  {
    id: "dossie.compartilhar",
    name: "Compartilhar versão do dossiê",
    status: "observed",
    transport: "POST /api/assets/objects/:id/shares",
    source: "app/server/assets/store.ts",
    symbol: "AssetsStore.share",
    effects: ["compartilhamento", "versionamento"],
    errors: [
      "SESSION_EXPIRED",
      "FORBIDDEN",
      "STALE_REVISION",
      "INVALID_INPUT",
      "UNAVAILABLE",
    ],
    notes:
      "Exige papel de envio, destinatário, finalidade, revisão exata, requisitos e idempotência. Retorna snapshot e recibo persistidos. Nova versão não amplia concessão antiga. Persistência local; não certifica operação distribuída.",
  },
  {
    id: "organizacao.gerir",
    name: "Gerir equipe e convites",
    status: "observed",
    transport: "POST /api/assets/{organization,invitations,members/:id}",
    source: "app/server/assets/store.ts",
    symbol: "AssetsStore.invite",
    effects: ["identidade", "permissao"],
    errors: [
      "SESSION_EXPIRED",
      "FORBIDDEN",
      "STALE_REVISION",
      "INVALID_INPUT",
      "UNAVAILABLE",
    ],
    notes:
      "Admin cria link manual de convite; colaborador tem escopo de objeto. Sem envio de e-mail. Revogar nega aceitação e encerrar vínculo nega sessão. Persistência local; não certifica operação distribuída.",
  },
  {
    id: "compartilhamento.consultar",
    name: "Consultar versão recebida",
    status: "observed",
    transport:
      "GET /api/assets/received/:id; GET /api/assets/evidence/:id?share=:id",
    source: "app/server/assets/store.ts",
    symbol: "AssetsStore.received",
    effects: ["leitura", "arquivo"],
    errors: [
      "SESSION_EXPIRED",
      "FORBIDDEN",
      "STALE_REVISION",
      "INVALID_INPUT",
      "UNAVAILABLE",
    ],
    notes:
      "Confere destinatário, vigência, versão e permissão de download em cada consulta. Persistência local; não certifica operação distribuída.",
  },
  {
    id: "compartilhamento.revogar",
    name: "Revogar acesso externo",
    status: "observed",
    transport: "POST /api/assets/shares/:id/revoke",
    source: "app/server/assets/store.ts",
    symbol: "AssetsStore.revokeShare",
    effects: ["permissao"],
    errors: [
      "SESSION_EXPIRED",
      "FORBIDDEN",
      "STALE_REVISION",
      "INVALID_INPUT",
      "UNAVAILABLE",
    ],
    notes:
      "Nega novas consultas; não promete apagar cópias baixadas. Persistência local; não certifica operação distribuída.",
  },
  {
    id: "solicitacao.criar",
    name: "Receber pedido de outra organização",
    status: "observed",
    transport:
      "POST /api/assets/requests; POST /api/assets/requests/:id/clarifications",
    source: "app/server/assets/store.ts",
    symbol: "AssetsStore.createRequest",
    effects: ["escrita", "notificacao"],
    errors: [
      "SESSION_EXPIRED",
      "FORBIDDEN",
      "STALE_REVISION",
      "INVALID_INPUT",
      "UNAVAILABLE",
    ],
    notes:
      "Contrato implementado para cliente solicitante, sem interface Investors nesta entrega. Isola organização destinatária; esclarecimento exige concessão vigente. Persistência local; não certifica operação distribuída.",
  },
  proposed(
    "analise.solicitarEsclarecimento",
    "Solicitar esclarecimento",
    ["escrita", "texto-livre"],
    ["SEM_PERMISSAO", "VERSAO_DESATUALIZADA", "INDISPONIVEL"],
    "Vincular pergunta a requisito/documento da versão analisada.",
  ),
  proposed(
    "analise.registrarDecisao",
    "Registrar decisão fundamentada",
    ["escrita", "decisao", "texto-livre"],
    [
      "SEM_PERMISSAO",
      "VERSAO_DESATUALIZADA",
      "PENDENCIAS_ABERTAS",
      "INDISPONIVEL",
    ],
    "Decisão humana, com finalidade e versão. Não altera Valid/Invalid do selo.",
  ),
];
