import type { AppId, Screen } from "./types";

function current(
  id: string,
  app: AppId,
  name: string,
  path: string,
  file: string,
  objective: string,
  operations: string[] = [],
  notes = "Estados, operações restantes e autorização ainda precisam de auditoria.",
  kind: Screen["kind"] = "page",
): Screen {
  return {
    id,
    app,
    name,
    objective,
    owner: "Produto + engenharia",
    lifecycle: "existing",
    route: { path, origin: app === "web" ? "web" : "app" },
    kind,
    source: file,
    operations,
    states: [],
    notes,
  };
}
function planned(
  id: string,
  app: AppId,
  name: string,
  path: string,
  objective: string,
  operations: string[] = [],
  states = ["carregando", "vazio", "indisponivel", "sem-permissao", "pronto"],
): Screen {
  return {
    id,
    app,
    name,
    objective,
    owner: "Produto + engenharia",
    lifecycle: "planned",
    route: { path, origin: "app" },
    kind: "page",
    operations,
    states,
    notes:
      "Proposta de rota e estados. Não há implementação nem contrato de backend aprovado. Referência: docs/LASTRE_PRODUCT_ARCHITECTURE.md.",
  };
}

const assetSources: Record<string, string> = {
  "LA-001": "Home",
  "LA-002": "ObjectList",
  "LA-003": "ObjectForm",
  "LA-004": "ObjectList",
  "LA-005": "ObjectDetail",
  "LA-006": "Requests",
  "LA-007": "Share",
  "LA-008": "Requests",
  "LA-009": "ObjectForm",
  "LA-010": "ObjectDetail",
  "LA-011": "Organization",
  "LA-012": "Auth",
  "LA-013": "Auth",
  "LA-014": "Received",
  "LA-015": "Share",
  "LA-016": "AssetsApp",
};
const assetOperations: Record<string, string[]> = {
  "LA-001": ["assets.consultar"],
  "LA-002": ["assets.consultar"],
  "LA-003": ["assets.salvar"],
  "LA-004": ["assets.consultar", "lote.importar"],
  "LA-005": ["assets.salvar", "evidencia.anexar", "dossie.compartilhar"],
  "LA-006": ["solicitacao.responder", "evidencia.anexar"],
  "LA-007": ["dossie.compartilhar", "destinatario.conferir"],
  "LA-008": ["assets.consultar"],
  "LA-009": ["assets.salvar"],
  "LA-010": ["assets.salvar", "evidencia.anexar", "dossie.compartilhar"],
  "LA-011": ["organizacao.gerir", "organizacao.alternar"],
  "LA-012": ["assets.autenticar"],
  "LA-013": ["organizacao.gerir"],
  "LA-014": ["compartilhamento.consultar"],
  "LA-015": ["dossie.compartilhar", "destinatario.conferir"],
  "LA-016": [],
};
function implementedAsset(
  id: string,
  app: AppId,
  name: string,
  path: string,
  objective: string,
  _operations: string[] = [],
  states = ["carregando", "vazio", "indisponivel", "sem-permissao", "pronto"],
): Screen {
  return {
    ...current(
      id,
      app,
      name,
      path,
      `app/src/features/assets/${assetSources[id]}.tsx`,
      objective,
      assetOperations[id],
    ),
    states,
    kind: id === "LA-016" ? "redirect" : "page",
    notes:
      "Implementação Assets com sessão HttpOnly, autorização por organização/cadastro e persistência atômica em arquivo no servidor. Demonstração explícita e isolada. Infraestrutura local de instância única; produção distribuída, confirmação de e-mail e recuperação de senha permanecem fora desta entrega. Ver docs/LASTRE_ASSETS_IMPLEMENTATION.md.",
  };
}

export const screens: Screen[] = [
  current(
    "LC-001",
    "console",
    "Visão geral",
    "/console",
    "app/src/routes/Overview.tsx",
    "Acompanhar a atividade e os resultados técnicos da demonstração.",
  ),
  current(
    "LC-002",
    "console",
    "Lotes",
    "/lots",
    "app/src/routes/Lots.tsx",
    "Consultar a fila de lotes e abrir o detalhe contextual.",
    ["lote.listar", "lote.consultar"],
  ),
  current(
    "LC-003",
    "console",
    "Atalho para lote",
    "/lots/:assetId",
    "app/src/routes/LotDetail.tsx",
    "Preservar links de lote, abrindo /lots?lot=:assetId.",
    [],
    "Redireciona para o drawer da lista. Não é uma segunda página de detalhe.",
    "redirect",
  ),
  current(
    "LC-004",
    "console",
    "Processamento",
    "/process",
    "app/src/routes/Process.tsx",
    "Executar e acompanhar o processamento de lotes.",
    ["lote.processar"],
  ),
  current(
    "LC-005",
    "console",
    "Auditoria",
    "/audit",
    "app/src/routes/Audit.tsx",
    "Consultar o histórico técnico de verificações.",
    ["auditoria.listar"],
  ),
  current(
    "LC-006",
    "console",
    "Detalhe da auditoria",
    "/audit/:assetId",
    "app/src/routes/AuditDetail.tsx",
    "Inspecionar a evidência e os resultados de um lote.",
    ["auditoria.consultar"],
  ),
  current(
    "LC-007",
    "console",
    "Atalho de cadeia",
    "/chain",
    "app/src/LegacyApp.tsx",
    "Encaminhar links antigos para /audit.",
    [],
    "Navigate para /audit. Chain.tsx não é a tela montada nesta rota.",
    "redirect",
  ),
  current(
    "LC-008",
    "console",
    "Exceções",
    "/escalations",
    "app/src/routes/Escalations.tsx",
    "Consultar e encaminhar exceções do processamento.",
    ["excecao.listar"],
  ),
  current(
    "LC-009",
    "console",
    "Configurações",
    "/settings",
    "app/src/routes/Settings.tsx",
    "Ajustar o modo de decisão operacional do agente.",
    ["configuracao.atualizar"],
  ),
  current(
    "LC-010",
    "console",
    "Captura",
    "/capture",
    "app/src/routes/Capture.tsx",
    "Organizar os dados de um artefato e calcular seu selo.",
    ["artefato.criar", "selo.calcular"],
  ),
  current(
    "LC-011",
    "console",
    "Marketplace demonstrativo",
    "/marketplace",
    "app/src/routes/Marketplace.tsx",
    "Explorar ativos fictícios e sua informação de origem.",
    ["lote.listar"],
    "Catálogo demonstrativo; não equivale ao futuro Lastre Investors.",
  ),
  current(
    "LC-012",
    "console",
    "Ativo no marketplace",
    "/marketplace/:assetId",
    "app/src/routes/MarketplaceAssetDetail.tsx",
    "Inspecionar um ativo da demonstração.",
    ["lote.consultar", "mint.simular", "rail.simular"],
  ),
  current(
    "LC-013",
    "console",
    "Minha coleção demo",
    "/my-assets",
    "app/src/routes/MyAssets.tsx",
    "Consultar a coleção demonstrativa da sessão.",
    [],
    "Não equivale ao cadastro patrimonial do futuro Lastre Assets.",
  ),
  current(
    "LC-014",
    "console",
    "Item da coleção demo",
    "/my-assets/:assetId",
    "app/src/routes/MyAssetDetail.tsx",
    "Inspecionar um item da coleção demonstrativa.",
    ["lote.consultar"],
  ),
  current(
    "LC-015",
    "console",
    "Agentes",
    "/agents",
    "app/src/routes/Agents.tsx",
    "Explorar a integração de consultas de proveniência.",
    ["consulta.simular"],
  ),
  current(
    "ID-001",
    "identity",
    "Login demonstrativo",
    "/login",
    "app/src/routes/Login.tsx",
    "Entrar na experiência demonstrativa.",
    [],
    "Perfil local não comprova identidade nem permissão de admin.",
  ),
  current(
    "ID-002",
    "identity",
    "Boas-vindas",
    "/welcome",
    "app/src/routes/Welcome.tsx",
    "Escolher um perfil de exploração da demo.",
  ),
  current(
    "DS-001",
    "design",
    "Design system",
    "/design-system",
    "app/src/routes/DesignSystem.tsx",
    "Consultar tokens, componentes e critérios visuais.",
    [],
    "Entrada especial em main.tsx, fora de App.tsx.",
  ),
  current(
    "AD-001",
    "admin",
    "Inventário vivo",
    "/admin/inventario",
    "app/src/routes/admin/Inventory.tsx",
    "Confrontar o produto planejado com as rotas presentes no código.",
    [],
    "Página única no Admin, com visões locais por ?view=. Cada ficha abre um drawer com abas: Visão geral, Contrato, Estados, Operações e Fluxos. Seleção por ?screen= e ?tab=. Prévia local, somente leitura, removida do build de produção. Não autentica administradores.",
  ),
  current(
    "LW-001",
    "web",
    "Site público",
    "/",
    "web/src/App.tsx",
    "Apresentar a Lastre e sua infraestrutura de prova.",
    [],
    "Leitura manual: adaptador de web/ ainda não implementado.",
  ),
  current(
    "LW-002",
    "web",
    "Apresentações",
    "/decks",
    "web/src/decks/DecksApp.tsx",
    "Escolher uma apresentação.",
    [],
    "Leitura manual do roteamento por pathname; noindex não protege acesso.",
  ),
  current(
    "LW-003",
    "web",
    "Apresentação",
    "/decks/:slug",
    "web/src/decks/DecksApp.tsx",
    "Navegar pelo conteúdo de uma apresentação.",
    [],
    "Slug é variante de conteúdo, não uma nova identidade de tela.",
  ),
  current(
    "LW-004",
    "web",
    "Diagrama padrão",
    "/diagram",
    "web/src/diagram/DiagramApp.tsx",
    "Trabalhar no quadro padrão armazenado no navegador.",
  ),
  current(
    "LW-005",
    "web",
    "Diagrama",
    "/diagram/:slug",
    "web/src/diagram/DiagramApp.tsx",
    "Abrir um quadro identificado por slug.",
  ),
  implementedAsset(
    "LA-001",
    "assets",
    "Início de Assets",
    "/assets",
    "Retomar solicitações, rascunhos e pendências da organização.",
  ),
  implementedAsset(
    "LA-002",
    "assets",
    "Meus ativos",
    "/assets/ativos",
    "Encontrar os ativos cadastrados pela organização.",
  ),
  implementedAsset(
    "LA-003",
    "assets",
    "Cadastrar ativo",
    "/assets/ativos/novo",
    "Salvar um cadastro identificável e entender o que falta.",
  ),
  implementedAsset(
    "LA-004",
    "assets",
    "Lotes de produção",
    "/assets/lotes",
    "Identificar a produção e retomar o lote correto.",
  ),
  implementedAsset(
    "LA-005",
    "assets",
    "Dossiê do lote",
    "/assets/lotes/:loteId",
    "Organizar documentos, verificações e histórico do lote.",
  ),
  implementedAsset(
    "LA-006",
    "assets",
    "Responder solicitação",
    "/assets/solicitacoes/:solicitacaoId",
    "Reunir os requisitos pedidos por uma organização identificada.",
    [],
    [
      "carregando",
      "rascunho-incompleto",
      "salvando",
      "salvo",
      "upload-em-andamento",
      "falha-no-upload",
      "pronto-para-revisao",
      "pendencia-recebida",
      "conflito-de-edicao",
      "sessao-expirada",
      "sem-permissao",
      "indisponivel",
    ],
  ),
  implementedAsset(
    "LA-007",
    "assets",
    "Revisar compartilhamento",
    "/assets/lotes/:loteId/compartilhar",
    "Confirmar destinatário, finalidade e versão dos dados enviados.",
    ["dossie.compartilhar"],
    [
      "carregando",
      "indisponivel",
      "sem-permissao",
      "pronto",
      "revisao",
      "enviando",
      "sucesso",
      "duplicado",
      "versao-desatualizada",
      "destinatario-invalido",
      "requisitos-pendentes",
      "recibo",
    ],
  ),
  implementedAsset(
    "LA-008",
    "assets",
    "Solicitações",
    "/assets/solicitacoes",
    "Encontrar o pedido correto e identificar quem precisa agir.",
  ),
  implementedAsset(
    "LA-009",
    "assets",
    "Cadastrar lote",
    "/assets/lotes/novo",
    "Salvar o cadastro mínimo de produção e preservar o contexto da solicitação.",
  ),
  planned(
    "LI-001",
    "investors",
    "Início de Investors",
    "/investors",
    "Reconhecer os casos que precisam de ação do analista.",
  ),
  implementedAsset(
    "LA-010",
    "assets",
    "Dossiê do ativo",
    "/assets/ativos/:ativoId",
    "Organizar o cadastro, documentos e versões de um ativo duradouro.",
  ),
  implementedAsset(
    "LA-011",
    "assets",
    "Organização e equipe",
    "/assets/organizacao",
    "Gerir responsáveis, convites e permissões da organização.",
  ),
  implementedAsset(
    "LA-012",
    "assets",
    "Entrada em Assets",
    "/assets/entrar",
    "Entrar ou criar uma organização e retomar o destino solicitado.",
  ),
  implementedAsset(
    "LA-013",
    "assets",
    "Aceitar convite",
    "/assets/convites/:token",
    "Aceitar uma participação com papel e escopo explícitos.",
  ),
  implementedAsset(
    "LA-014",
    "assets",
    "Dossiê recebido",
    "/assets/recebidos/:shareId",
    "Consultar somente a versão e os documentos compartilhados com a organização.",
  ),
  implementedAsset(
    "LA-015",
    "assets",
    "Revisar compartilhamento de ativo",
    "/assets/ativos/:ativoId/compartilhar",
    "Revisar destinatário, finalidade e documentos do ativo antes de compartilhar.",
  ),
  implementedAsset(
    "LA-016",
    "assets",
    "Entrada principal",
    "/",
    "Encaminhar a entrada principal para Lastre Assets.",
  ),
  planned(
    "LI-002",
    "investors",
    "Análises",
    "/investors/analises",
    "Localizar um caso por objeto, organização e finalidade.",
  ),
  planned(
    "LI-003",
    "investors",
    "Detalhe da análise",
    "/investors/analises/:analiseId",
    "Examinar a versão recebida, seus requisitos e evidências.",
  ),
  planned(
    "LI-004",
    "investors",
    "Pedir esclarecimento",
    "/investors/analises/:analiseId/esclarecimento",
    "Pedir uma resposta vinculada a um documento ou requisito.",
    ["analise.solicitarEsclarecimento"],
  ),
  planned(
    "LI-005",
    "investors",
    "Registrar decisão",
    "/investors/analises/:analiseId/decisao",
    "Registrar uma conclusão humana com justificativa e versão analisada.",
    ["analise.registrarDecisao"],
  ),
];
