/** Deliberately fictional, immutable preview data. Never merged with product data. */
export const observedAt = "25 set. 2026, 10:42 BRT";
export const organizations = [
  {
    id: "ORG-014",
    name: "Horizonte Agro",
    initials: "HA",
    product: "Assets",
    status: "Ativa",
    owner: "Marina Costa",
    activity: "Hoje, 10:38",
    segment: "Agronegócio",
    contact: "operacao@horizonte.example",
    activation: "Primeiro envio concluído",
  },
  {
    id: "ORG-021",
    name: "Grupo Aurora",
    initials: "GA",
    product: "Investors",
    status: "Ativa",
    owner: "Rafael Lima",
    activity: "Hoje, 10:25",
    segment: "Análise de ativos",
    contact: "equipe@aurora.example",
    activation: "Primeira análise iniciada",
  },
  {
    id: "ORG-032",
    name: "Verde Cerrado",
    initials: "VC",
    product: "Assets",
    status: "Em ativação",
    owner: "Marina Costa",
    activity: "Hoje, 09:54",
    segment: "Agronegócio",
    contact: "equipe@cerrado.example",
    activation: "Convite aguardando aceite",
  },
  {
    id: "ORG-008",
    name: "Rio Claro Energia",
    initials: "RC",
    product: "Assets",
    status: "Ativa",
    owner: "Rafael Lima",
    activity: "Ontem, 16:40",
    segment: "Energia",
    contact: "ativos@rioclaro.example",
    activation: "Primeiro envio concluído",
  },
  {
    id: "ORG-041",
    name: "Serra Capital",
    initials: "SC",
    product: "Investors",
    status: "Convidada",
    owner: "Sem responsável",
    activity: "Ontem, 14:10",
    segment: "Análise de ativos",
    contact: "analises@serra.example",
    activation: "Identidade ainda não confirmada",
  },
  {
    id: "ORG-017",
    name: "Vale do Sol",
    initials: "VS",
    product: "Assets",
    status: "Suspensa",
    owner: "Marina Costa",
    activity: "23 set., 11:20",
    segment: "Agronegócio",
    contact: "equipe@valedosol.example",
    activation: "Restrição operacional em revisão",
  },
];
export const cases = [
  {
    id: "OC-104",
    title: "Fonte externa indisponível",
    type: "Falha técnica",
    priority: "Alta",
    organization: "ORG-014",
    stage: "Verificação",
    status: "Em atendimento",
    owner: "Marina Costa",
    wait: "1 h 24 min",
    updated: "10:38",
    object: "HZ-014",
    dossier: "DOS-014",
    version: "V-002",
    execution: "EX-204",
    description:
      "A fonte externa não respondeu. A versão 2 continua recebida; esta verificação ainda não produziu resultado.",
    next: "Confirmar a recuperação da fonte e revisar uma nova tentativa.",
  },
  {
    id: "OC-108",
    title: "Acesso ao documento interrompido",
    type: "Problema de acesso",
    priority: "Crítica",
    organization: "ORG-021",
    stage: "Leitura de evidência",
    status: "Nova",
    owner: "Sem responsável",
    wait: "38 min",
    updated: "10:34",
    object: "HZ-014",
    dossier: "DOS-014",
    version: "V-002",
    execution: "",
    description:
      "O vínculo da pessoa continua ativo. O compartilhamento consultado expirou; o documento permanece restrito.",
    next: "Orientar a organização a solicitar uma nova concessão ao responsável.",
  },
  {
    id: "OC-103",
    title: "Revisão de publicação de requisitos",
    type: "Aprovação administrativa",
    priority: "Normal",
    organization: "ORG-014",
    stage: "Publicação",
    status: "Aguardando aprovação",
    owner: "Rafael Lima",
    wait: "2 h 10 min",
    updated: "10:12",
    object: "HZ-014",
    dossier: "DOS-014",
    version: "V-002",
    execution: "",
    description:
      "O rascunho acrescenta a data de emissão ao laudo de origem. Casos recebidos manterão os requisitos anteriores.",
    next: "Revisar versão, vigência e organizações elegíveis.",
  },
  {
    id: "OC-101",
    title: "Convite do responsável expirou",
    type: "Atendimento de suporte",
    priority: "Normal",
    organization: "ORG-032",
    stage: "Ativação",
    status: "Aguardando terceiro",
    owner: "Marina Costa",
    wait: "4 h 05 min",
    updated: "09:54",
    object: "",
    dossier: "",
    version: "",
    execution: "",
    description:
      "A organização confirmou o endereço do responsável. A entrega anterior expirou antes do aceite.",
    next: "Revisar destinatário e elegibilidade de reenvio.",
  },
  {
    id: "OC-099",
    title: "Confirmar entrega de comunicação",
    type: "Falha técnica",
    priority: "Baixa",
    organization: "ORG-008",
    stage: "Comunicação",
    status: "Em triagem",
    owner: "Sem responsável",
    wait: "1 dia",
    updated: "09:18",
    object: "RC-008",
    dossier: "DOS-008",
    version: "V-001",
    execution: "",
    description:
      "O provedor aceitou a mensagem, mas não confirmou a entrega. Não há sinal de leitura.",
    next: "Consultar a entrega original antes de solicitar reenvio.",
  },
  {
    id: "OC-095",
    title: "Consulta da origem restabelecida",
    type: "Falha técnica",
    priority: "Normal",
    organization: "ORG-014",
    stage: "Verificação",
    status: "Resolvida",
    owner: "Rafael Lima",
    wait: "—",
    updated: "Ontem",
    object: "HZ-014",
    dossier: "DOS-014",
    version: "V-001",
    execution: "EX-201",
    description:
      "A tentativa concluiu com resultado inconclusivo. A recuperação técnica foi confirmada; a conclusão do cliente permanece inalterada.",
    next: "Acompanhar a análise no contexto da organização destinatária.",
  },
];
export const objects = [
  {
    id: "HZ-014",
    name: "Lote de soja · safra 2026",
    organization: "ORG-014",
    type: "Lote",
    status: "Compartilhado",
    quantity: "480 t",
    category: "Produção agrícola",
    location: "Rio Verde, GO",
    dossier: "DOS-014",
  },
  {
    id: "RC-008",
    name: "Usina Rio Claro",
    organization: "ORG-008",
    type: "Ativo",
    status: "Documentação em revisão",
    quantity: "12 MW",
    category: "Geração de energia",
    location: "Uberaba, MG",
    dossier: "DOS-008",
  },
  {
    id: "VC-032",
    name: "Lote de milho · segunda safra",
    organization: "ORG-032",
    type: "Lote",
    status: "Rascunho",
    quantity: "220 t",
    category: "Produção agrícola",
    location: "Jataí, GO",
    dossier: "DOS-032",
  },
];
export const dossiers = [
  {
    id: "DOS-014",
    name: "Origem do lote HZ-014",
    object: "HZ-014",
    organization: "ORG-014",
    recipient: "ORG-021",
    purpose: "Análise documental de origem",
    versions: ["V-001", "V-002"],
    latest: "V-002",
    status: "Recebido",
  },
  {
    id: "DOS-008",
    name: "Documentação da usina Rio Claro",
    object: "RC-008",
    organization: "ORG-008",
    recipient: "ORG-021",
    purpose: "Análise de titularidade",
    versions: ["V-001"],
    latest: "V-001",
    status: "Recebido",
  },
  {
    id: "DOS-032",
    name: "Origem do lote VC-032",
    object: "VC-032",
    organization: "ORG-032",
    recipient: "",
    purpose: "Preparação documental",
    versions: ["Rascunho"],
    latest: "Rascunho",
    status: "Rascunho",
  },
];
export const evidence = [
  {
    id: "EVD-014",
    name: "Declaração de origem",
    dossier: "DOS-014",
    version: "V-002",
    status: "Disponível na demonstração",
    author: "Ana Ribeiro",
    date: "25 set. 2026, 09:12 BRT",
    requirement: "Identificação da origem",
    preview: true,
  },
  {
    id: "EVD-013",
    name: "Declaração de origem anterior",
    dossier: "DOS-014",
    version: "V-001",
    status: "Versão histórica",
    author: "Ana Ribeiro",
    date: "24 set. 2026, 16:20 BRT",
    requirement: "Identificação da origem",
    preview: true,
  },
  {
    id: "EVD-015",
    name: "Laudo de classificação",
    dossier: "DOS-014",
    version: "V-002",
    status: "Conteúdo restrito",
    author: "Ana Ribeiro",
    date: "25 set. 2026, 09:14 BRT",
    requirement: "Classificação do lote",
    preview: false,
  },
  {
    id: "EVD-008",
    name: "Comprovante de titularidade",
    dossier: "DOS-008",
    version: "V-001",
    status: "Sem prévia",
    author: "Bruno Teixeira",
    date: "24 set. 2026, 14:00 BRT",
    requirement: "Titularidade do ativo",
    preview: false,
  },
];
export const analyses = [
  {
    id: "AN-042",
    name: "Análise de origem · HZ-014",
    dossier: "DOS-014",
    organization: "ORG-021",
    owner: "Camila Nunes",
    status: "Aguardando verificação",
    version: "V-001",
    request: "SOL-042",
  },
  {
    id: "AN-038",
    name: "Análise de titularidade · RC-008",
    dossier: "DOS-008",
    organization: "ORG-021",
    owner: "Camila Nunes",
    status: "Em análise",
    version: "V-001",
    request: "SOL-038",
  },
];
export const executions = [
  {
    id: "EX-204",
    name: "Consulta de origem",
    object: "HZ-014",
    organization: "ORG-014",
    dossier: "DOS-014",
    version: "V-002",
    method: "MET-001",
    methodVersion: "3",
    status: "Falhou",
    result: "Não produzido",
    validity: "Não aplicável",
    started: "25 set., 09:18",
    duration: "32 s",
    integration: "INTG-001",
    retry: true,
  },
  {
    id: "EX-203",
    name: "Consistência documental",
    object: "HZ-014",
    organization: "ORG-014",
    dossier: "DOS-014",
    version: "V-002",
    method: "MET-002",
    methodVersion: "1",
    status: "Concluída",
    result: "Divergente",
    validity: "Vigente",
    started: "25 set., 09:15",
    duration: "4 s",
    integration: "INTG-002",
    retry: false,
  },
  {
    id: "EX-201",
    name: "Consulta de origem",
    object: "HZ-014",
    organization: "ORG-014",
    dossier: "DOS-014",
    version: "V-001",
    method: "MET-001",
    methodVersion: "3",
    status: "Concluída",
    result: "Inconclusivo",
    validity: "Vigente",
    started: "24 set., 16:28",
    duration: "12 s",
    integration: "INTG-001",
    retry: false,
  },
  {
    id: "EX-198",
    name: "Consistência documental",
    object: "RC-008",
    organization: "ORG-008",
    dossier: "DOS-008",
    version: "V-001",
    method: "MET-002",
    methodVersion: "1",
    status: "Em espera",
    result: "Não produzido",
    validity: "Não aplicável",
    started: "24 set., 14:08",
    duration: "—",
    integration: "INTG-002",
    retry: false,
  },
];
export const models = [
  {
    id: "MOD-001",
    name: "Documentação de origem agrícola",
    type: "Requisitos",
    owner: "Lastre",
    version: "3",
    status: "Publicado",
    scope: "Ativos e lotes agrícolas",
    description:
      "Identificação da origem, declaração do responsável e classificação do lote.",
    requirements: [
      "Identificação da origem",
      "Declaração do responsável",
      "Classificação do lote",
    ],
  },
  {
    id: "MOD-002",
    name: "Titularidade de geração de energia",
    type: "Requisitos",
    owner: "Lastre",
    version: "1",
    status: "Em revisão",
    scope: "Ativos de energia",
    description:
      "Documentos que identificam o ativo, a capacidade instalada e a titularidade.",
    requirements: ["Identificação do ativo", "Comprovante de titularidade"],
  },
  {
    id: "TIP-001",
    name: "Lote agrícola",
    type: "Tipos de objeto",
    owner: "Lastre",
    version: "2",
    status: "Publicado",
    scope: "Lastre Assets",
    description:
      "Campos de origem, safra, quantidade, unidade e responsável pela declaração.",
    requirements: ["Safra", "Quantidade em toneladas", "Local de origem"],
  },
  {
    id: "MET-001",
    name: "Consulta de origem",
    type: "Métodos",
    owner: "Equipe técnica",
    version: "3",
    status: "Publicado",
    scope: "Dossiês com identificação de origem",
    description:
      "Consulta a fonte declarada. Indisponibilidade não produz divergência documental.",
    requirements: [
      "Referência da fonte",
      "Identificação da origem",
      "Versão do dossiê",
    ],
  },
  {
    id: "MET-002",
    name: "Consistência documental",
    type: "Métodos",
    owner: "Equipe técnica",
    version: "1",
    status: "Publicado",
    scope: "Campos declarados e evidências",
    description:
      "Confere consistência entre campos, sem emitir decisão de investimento.",
    requirements: ["Campos declarados", "Referências de evidências"],
  },
];
export const integrations = [
  {
    id: "INTG-001",
    name: "Fonte de origem",
    category: "Verificação",
    owner: "Equipe técnica",
    health: "Degradado",
    lastSuccess: "Hoje, 09:02",
    purpose: "Consulta de referências da origem declarada",
    flow: "Verificação de origem",
    credential: "cred_origem_••••27",
    observed: "10:42",
  },
  {
    id: "INTG-002",
    name: "Armazenamento de evidências",
    category: "Documentos",
    owner: "Plataforma",
    health: "Operacional",
    lastSuccess: "Hoje, 10:38",
    purpose: "Recebimento e leitura autorizada de arquivos",
    flow: "Envio e leitura de evidências",
    credential: "cred_files_••••14",
    observed: "10:42",
  },
  {
    id: "INTG-003",
    name: "Entrega de comunicações",
    category: "Comunicação",
    owner: "Operação",
    health: "Desconhecido",
    lastSuccess: "Hoje, 08:50",
    purpose: "Entrega de convites e avisos de nova versão",
    flow: "Convites e notificações",
    credential: "cred_mail_••••08",
    observed: "08:50",
  },
];
export const deliveries = [
  {
    id: "ENT-104",
    name: "Convite do responsável",
    organization: "ORG-032",
    destination: "e••••@cerrado.example",
    status: "Expirado",
    attempts: 1,
    time: "24 set., 09:00",
    retry: true,
  },
  {
    id: "ENT-099",
    name: "Material recebido",
    organization: "ORG-008",
    destination: "a••••@aurora.example",
    status: "Aceito pelo provedor",
    attempts: 1,
    time: "24 set., 16:40",
    retry: false,
  },
];
export const people = [
  {
    id: "PES-001",
    name: "Ana Ribeiro",
    initials: "AR",
    email: "ana@horizonte.example",
    organization: "ORG-014",
    role: "Responsável pelo envio",
    type: "Pessoas",
    status: "Ativo",
    last: "Hoje, 10:38",
  },
  {
    id: "PES-002",
    name: "Camila Nunes",
    initials: "CN",
    email: "camila@aurora.example",
    organization: "ORG-021",
    role: "Analista",
    type: "Pessoas",
    status: "Ativo",
    last: "Hoje, 10:25",
  },
  {
    id: "PES-003",
    name: "Marina Costa",
    initials: "MC",
    email: "marina@lastre.example",
    organization: "",
    role: "Operação e suporte",
    type: "Equipe interna",
    status: "Ativo",
    last: "Hoje, 10:42",
  },
  {
    id: "PES-004",
    name: "Rafael Lima",
    initials: "RL",
    email: "rafael@lastre.example",
    organization: "",
    role: "Responsável técnico",
    type: "Equipe interna",
    status: "Ativo",
    last: "Hoje, 10:12",
  },
];
export const events = [
  {
    id: "EVT-504",
    time: "25 set., 10:38:24",
    actor: "Marina Costa",
    action: "Ocorrência atribuída",
    target: "OC-104",
    organization: "ORG-014",
    result: "Confirmado",
    reason: "Continuidade da investigação da fonte externa.",
    correlation: "COR-204",
  },
  {
    id: "EVT-503",
    time: "25 set., 10:12:08",
    actor: "Rafael Lima",
    action: "Revisão solicitada",
    target: "INT-103",
    organization: "ORG-014",
    result: "Aguardando aprovação",
    reason: "Nova versão de requisitos para solicitações futuras.",
    correlation: "COR-103",
  },
  {
    id: "EVT-502",
    time: "25 set., 09:18:32",
    actor: "Serviço de verificação",
    action: "Tentativa encerrada",
    target: "EX-204",
    organization: "ORG-014",
    result: "Falhou",
    reason: "A fonte externa não respondeu no prazo de consulta.",
    correlation: "COR-204",
  },
  {
    id: "EVT-501",
    time: "25 set., 09:14:00",
    actor: "Ana Ribeiro",
    action: "Versão recebida",
    target: "DOS-014",
    organization: "ORG-014",
    result: "Confirmado",
    reason: "Envio da versão V-002 para Grupo Aurora.",
    correlation: "COR-202",
  },
];
export const interventions = [
  {
    id: "INT-103",
    name: "Publicar requisitos de origem · versão 4",
    status: "Aguardando aprovação",
    author: "Rafael Lima",
    organization: "ORG-014",
    target: "MOD-001",
    version: "4",
    effect:
      "Novas solicitações do piloto usarão a data de emissão como requisito. Casos já enviados mantêm a versão 3.",
    reason: "Tornar explícita a emissão do laudo para solicitações futuras.",
    kind: "Publicação",
    eligible: ["Novas solicitações de Horizonte Agro"],
    excluded: ["DOS-014 · versões V-001 e V-002 já recebidas"],
    reviewer: "Produto e qualidade",
  },
  {
    id: "INT-104",
    name: "Repetir consulta de origem · HZ-014",
    status: "Resultado desconhecido",
    author: "Marina Costa",
    organization: "ORG-014",
    target: "EX-204",
    version: "V-002",
    effect:
      "Nova tentativa com a mesma entrada e método 3. A decisão de Grupo Aurora permanece inalterada.",
    reason: "Recuperação após indisponibilidade da fonte externa.",
    kind: "Recuperação",
    eligible: ["EX-204 · DOS-014 / V-002"],
    excluded: ["EX-201 · versão histórica V-001"],
    reviewer: "Responsável técnico",
  },
  {
    id: "INT-105",
    name: "Revisar exportação de eventos",
    status: "Em preparação",
    author: "Marina Costa",
    organization: "ORG-014",
    target: "ORG-014",
    version: "Seleção 1",
    effect:
      "Arquivo limitado a metadados operacionais de 24 a 25 de setembro. Sem conteúdo documental.",
    reason: "Atendimento de pedido de dados identificado.",
    kind: "Exportação",
    eligible: ["Metadados de auditoria de ORG-014"],
    excluded: ["Documentos, notas privadas e credenciais"],
    reviewer: "Responsável por dados",
  },
];
export function organizationName(id: string) {
  return (
    organizations.find((item) => item.id === id)?.name ??
    (id ? "Organização indisponível" : "Lastre · equipe interna")
  );
}
export function recordUrl(id: string): string {
  if (id.startsWith("OC-")) return `/admin/fila/${id}`;
  if (id.startsWith("ORG-")) return `/admin/organizacoes/${id}`;
  if (id.startsWith("DOS-"))
    return `/admin/dossies/${id}?versao=${dossiers.find((d) => d.id === id)?.latest ?? "V-001"}`;
  if (id.startsWith("EX-")) return `/admin/verificacoes/${id}`;
  if (id.startsWith("INT-")) return `/admin/intervencoes/${id}`;
  if (/^(MOD|MET|TIP)-/.test(id)) return `/admin/modelos/${id}`;
  return "/admin/registros";
}
